### PR TITLE
Own Grid Framework Completed

### PR DESCRIPTION
**Pull request by abruzy**

### CODE REVIEW

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great work team :clap: . However, I think that you misunderstood the concept of the project. I'll explain below :arrow_down: 

##### First part
- You are supposed to design a **responsive** css framework that is similar to bootstrap (i.e not as complicated though) where you add classes that helps you accelerate designing your project.
- To showcase the 12 cols **responsive** grid system of your framework, you create a simple page (i.e **colored boxes as you did**) and you use the classes of the framework to style your page.

##### Second Part
- You use **your framework** to design a page of your choice (i.e. clone or from your imagination).
  - Please carefully read the project's assignment on odin website.

### Please adjust your project as suggested. When finished, submit another code review request

###### PS: contact me on slack if you want more clarifications

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Hi team, 

The update my colleague asked for, hasn't been implemented. 

Watch this [video](https://www.youtube.com/watch?v=4WcsGHrbobE&t=1s), use it as a guide.

After implementing the necessary changes, submit another form for code review.

**```Have a great day```**  :slightly_smiling_face:

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Nice Try :+1: 
You are still far from completing this project. Carefully read and implement changes requested by the previous reviewers.
Please take your time in building this project as it can be tricky and most people don't understand the requirements.
Please make the changes and re-submit.

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Awesome :+1: 
I see you have made changes as requested. But your grid still lacks breakpoint classes.
- [ ] define column classes with breakpoints such as ```col-lg-1```, ```col-lg-2```, ```col-md-1``` and so forth.
- [ ] your clone should a web page that utilizes your grid system. a good example of such sites is [pixel](https://www.pixel.com).

### Please make those changes and submit for another review.

**Review by Forison — COMMENTED** [review]
# Pull request under review by Addo

**Review by Forison — CHANGES_REQUESTED** [review]
# Hi team 👋👋
You have done well🙂 however, you did not address all issues that the previous review sought you to address.😔
your project implementation seems to make use of only ```col-sm```😔.  I would prefer you try to clone an actual simple web page, that way, you would be able to use different custom classes that you created 😔.I would be glad to see a ```.navbar``` different col classes usage, custom background-colors, etc... 
#### The page to clone must not necessarily be a complex one🙂 . 
A simple web page like [this](https://gridbyexample.com/examples/) won't be a bad idea
### Kindly clone the page I suggested or(a simpler web page of your choice) and submit for review

feel free to contact me on [LinkedIn](https://www.linkedin.com/in/forison-addo-558201159/), [Twitter](https://twitter.com/ADDOBOAKYE1) or slack for further clarification if necessary. I would be happy to assist you.
Happy coding😇😇😇

**Review by wathigo — APPROVED** [review]
## Hi @abruzy  :wave:  
### You have put great effort on the project!
Before merging the branch to master,
Please update your stickler configurations to exclude files in `sass` directory  files from being scanned for errors.
```
linters:
    flake8:
    eslint:
        config: './eslint.config'
    csslint:

files:
    ignore:
        - 'sass/*'
```
**This is approved!** 
_Reviewed by `Simon Wathigo`
Good luck in your future projects_

**Pull request merged**
